// LaTeX formula strings — double-escaped so minifiers cannot alter them
export const L2_0 = "C = S_0 e^{-qT} N(d_1) - K e^{-rT} N(d_2)"
export const L2_1 = "d_1 = \\frac{\\ln(S_0/K) + (r - q + \\frac{1}{2}\\sigma^2)T}{\\sigma\\sqrt{T}}, \\quad d_2 = d_1 - \\sigma\\sqrt{T}"
export const L2_2 = "N(\\cdot)"
export const L2_3 = "N(d_2)"
export const L2_4 = "N(d_1)"
export const L2_5 = "\\sigma"
export const L2_6 = "\\sigma"
export const L3_0 = "\\sigma"
export const L3_1 = "v_t"
export const L3_2 = "dS_t = r S_t \\, dt + \\sqrt{v_t} \\, S_t \\, dW^1_t"
export const L3_3 = "dv_t = \\kappa(\\theta - v_t) \\, dt + \\sigma \\sqrt{v_t} \\, dW^2_t"
export const L3_4 = "dW^1_t \\, dW^2_t = \\rho \\, dt"
export const L3_5 = "r"
export const L3_6 = "dW^1_t"
export const L3_7 = "\\sqrt{v_t}"
export const L3_8 = "\\theta"
export const L3_9 = "\\kappa"
export const L3_10 = "dW^2_t"
export const L3_11 = "\\rho"
export const L3_12 = "2\\kappa\\theta > \\sigma^2"
export const L3_13 = "\\rho < 0"
export const L3_14 = "\\sigma"
export const L4_0 = "S_T"
export const L4_1 = "X"
export const L4_2 = "\\phi(u) = \\mathbb{E}\\left[e^{iuX}\\right]"
export const L4_3 = "X"
export const L4_4 = "u"
export const L4_5 = "\\ln S_T"
export const L4_6 = "\\phi_T(u) = \\mathbb{E}\\left[e^{iu \\ln S_T}\\right] = e^{C(u,T) + D(u,T) v_0 + iu \\ln S_0}"
export const L4_7 = "C"
export const L4_8 = "D"
export const L4_9 = "\\kappa, \\theta, \\sigma, \\rho"
export const L4_10 = "T"
export const L4_11 = "C = S_0 e^{-qT} P_1 - K e^{-rT} P_2"
export const L4_12 = "P_j = \\frac{1}{2} + \\frac{1}{\\pi} \\int_0^\\infty \\text{Re}\\left[\\frac{e^{-iu\\ln K} \\phi_j(u)}{iu}\\right] du"
export const L4_13 = "P_2"
export const L4_14 = "P_1"
export const L4_15 = "O(N^2)"
export const L4_16 = "O(N \\log N)"
export const L5_0 = "\\kappa, \\theta, \\sigma, \\rho, v_0"
export const L5_1 = "\\min_{\\kappa,\\theta,\\sigma,\\rho,v_0} \\sum_{i=1}^{N} \\left( C_{\\text{model}}(K_i, T_i) - C_{\\text{market}}(K_i, T_i) \\right)^2"
export const L5_2 = "\\sigma"
export const L5_3 = "\\rho"
